title: "The no-bullshit ZTNA vendor directory"

description:
  - text: This vendor directory is curated and maintained by the team at <a href="https://enclave.io" target="_blank">https://enclave.io</a> and other <a href="https://github.com/zerotrustnetworkaccess/zerotrustnetworkaccess.info/graphs/contributors" target="_blank">contributors</a>.
  - text: Like us, you might also be fed up with the hype and outlandish Zero Trust marketing claims being made by (some) frothing vendors. We built this site to help bring a little clarity back to the conversation and highlight the different architectures and options available.
  - text: We believe the community as a whole benefits from an impartial, engineering-led and open-source resource to help better understand this emerging technology, so we've made the source code for this directory available on <a href="https://github.com/zerotrustnetworkaccess/zerotrustnetworkaccess.info" target="_blank">GitHub</a> and all the data is published under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">Creative Commons</a> license.
  - text: Keeping the directory up to date and accurate requires a lot of work and while we maintain the vendor list on a best-effort basis, we welcome and encourage readers to submit a <a href="https://github.com/zerotrustnetworkaccess/zerotrustnetworkaccess.info/pulls" target="_blank">pull request</a> via GitHub to address any inaccuracies or omissions in the list.

enclave_logo_1x: "/assets/images/enclave_logo.png"
enclave_logo_2x: "/assets/images/enclave_logo@2x.png"
enclave_logo_light_1x: "/assets/images/enclave_logo_light.png"
enclave_logo_light_2x: "/assets/images/enclave_logo_lighto@2x.png"

black_logo_1x: "/assets/images/logo.png"
black_logo_2x: "/assets/images/logo@2x.png"

light_logo_1x: "/assets/images/logo-light.png"
light_logo_2x: "/assets/images/logo-light@2x.png"

copyright_text: "© 2022 Enclave Networks. All rights reserved."

google_analytics:
  enable: true
  key: "G-XW7G2V52ZN"

footer_newsletter:
  title: "Our Newsletter"
  sub_title: "Subscribe to our newsletter to get our news & deals delivered to your inbox!"
  subscribe_button_text: "Join"

author_page_header:
  header_background_image: "/assets/images/art/bg31.jpg"

gallery:
  images:
    - img: "/assets/images/art/z1.svg"
    - img: "/assets/images/art/z2.svg"
    - img: "/assets/images/art/z3.svg"
    - img: "/assets/images/art/z4.svg"
    - img: "/assets/images/art/z5.svg"
    - img: "/assets/images/art/z6.svg"
    - img: "/assets/images/art/z7.svg"
    - img: "/assets/images/art/z8.svg"
